spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://give-me-a-gift-database.cuj50dozcrxf.ap-northeast-2.rds.amazonaws.com:3306/project1?serverTimezone=Asia/Seoul
    username: admin
    password: 14571457
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug